### ISSUE TITLE
Failure to create

### ISSUE THREAD

**Issue by jannostudio** [philschmid/cdk-samples#6]
Hey, has there been a change to how a serverless endpoint is deployed? 

```09:38:07 | CREATE_FAILED        | AWS::SageMaker::Endpoint       | SagemakerEndpointhfendpointE7336632
Request to service failed. If failure persists after retry, contact customer support.

        /tmp/tmpa44vq3sx/lib/program.js:8432:58
        \_ Kernel._wrapSandboxCode (/tmp/tmpa44vq3sx/lib/program.js:8860:24)
        \_ Kernel._create (/tmp/tmpa44vq3sx/lib/program.js:8432:34)
        \_ Kernel.create (/tmp/tmpa44vq3sx/lib/program.js:8173:29)
        \_ KernelHost.processRequest (/tmp/tmpa44vq3sx/lib/program.js:9757:36)
        \_ KernelHost.run (/tmp/tmpa44vq3sx/lib/program.js:9720:22)
        \_ Immediate._onImmediate (/tmp/tmpa44vq3sx/lib/program.js:9721:46)
        \_ processImmediate (node:internal/timers:464:21)


 ❌  HuggingfaceServerlessSagemakerEndpoint failed: Error: The stack named HuggingfaceServerlessSagemakerEndpoint failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at waitForStackDeploy (/home/jan/.nvm/versions/node/v17.1.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/home/jan/.nvm/versions/node/v17.1.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:355:26)
    at CdkToolkit.deploy (/home/jan/.nvm/versions/node/v17.1.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:208:24)
    at initCommandLine (/home/jan/.nvm/versions/node/v17.1.0/lib/node_modules/aws-cdk/lib/cli.ts:310:12)

The stack named HuggingfaceServerlessSagemakerEndpoint failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE ```

**Comment by philschmid** [comment]
Could you please provide some context? What are you trying to do? What steps lead to this error? What do you see when you go to cloudformation?

**Comment by jannostudio** [comment]
> Could you please provide some context? What are you trying to do? What steps lead to this error? What do you see when you go to cloudformation?

Sorry, i am trying to deploy your example (or my own serverless) endpoint and it fails at the creation of the endpoint. Normal Endpoints deploy fine and your stack worked perfectly fine until yesterday evening. Is your example working for you at the moment?

Cloudformation fails at endpoint creation and then tries to rollback.

**Comment by philschmid** [comment]
I successfully create a SageMaker Serverless Endpoint with the `sagemaker-serverless-huggingface-endpoint/` CDK code. 
Which CDK version do you have installed? I create the samples with 1.x maybe 2.x introduce changes.

**Comment by jannostudio** [comment]
Issue was a different one, i am just an idiot.
