### ISSUE TITLE
HuggingFace SageMaker : cannot pull image

### ISSUE THREAD

**Issue by ierezell** [philschmid/cdk-samples#7]
Hello, 

First, thanks a lot for all those templates! They're really useful. 

I was reproducing the `Huggingface Sagemaker` (but with an Async Inference version as a test) with the typescript CDK but I cannot deploy it due to the following error. 

Here is the stack (I also have the same `cdk.json` flags): 

<details>
<summary> Typescript stack </summary>
</br>

```typescript

import * as cdk from 'aws-cdk-lib'
import { Construct } from 'constructs';

function getImageUri(useGpu: boolean): string
{
  const region: string = cdk.Aws.REGION
  const transformerVersion = "4.17.0"
  const pytorchVersion = "1.10.2"
  const pythonVersion = "38"

  const regionNb = "763104351884"
  const arch = useGpu ? `gpu-py${pythonVersion}-cu113` : `cpu-py${pythonVersion}`
  const repo = `${regionNb}.dkr.ecr.${region}.amazonaws.com/huggingface-pytorch-inference`
  const tag = `${pytorchVersion}-transformers${transformerVersion}-${arch}-ubuntu20.04`

  // Trying to hardcode the image URI without success. 
  // return "763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04"
  return `${repo}:${tag}`
}
function isGpuInstance(instanceType: string): boolean
{
  return ["g", "p"].includes(instanceType.split('.')[1][0].toLowerCase())
}

export class AsyncStack extends cdk.Stack
{
  constructor(scope: Construct, id: string, props: cdk.StackProps)
  {
    super(scope, id, props)

    const instanceType = "ml.g4dn.xlarge"

    const sagemakerRole = new cdk.aws_iam.Role(
      this, "MySagemakerRole", {
      assumedBy: new cdk.aws_iam.ServicePrincipal("sagemaker.amazonaws.com")
    })

    sagemakerRole.addToPolicy(new cdk.aws_iam.PolicyStatement(
      {
        resources: ["*"],
        actions: [
          "*",
          "sagemaker:*",
          "kms:Decrypt",
          "ssm:GetParameters",
          "secretsmanager:GetSecretValue",
          'ecr:GetAuthorizationToken',
          'ecr:GetDownloadUrlForLayer',
          'ecr:BatchGetImage',
          "ecr:*",
          "s3:*",
          "ecr:GetDownloadUrlForLayer",
          "ecr:BatchGetImage",
          "ecr:BatchCheckLayerAvailability",
          "ecr:GetAuthorizationToken",
          "cloudwatch:PutMetricData",
          "cloudwatch:GetMetricData",
          "cloudwatch:GetMetricStatistics",
          "cloudwatch:ListMetrics",
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:DescribeLogStreams",
          "logs:PutLogEvents",
          "logs:GetLogEvents",
          "s3:CreateBucket",
          "s3:ListBucket",
          "s3:GetBucketLocation",
          "s3:GetObject",
          "s3:PutObject",
        ],
        sid: 'AllowECRLoginAndPull',
      }))

    const model = new cdk.aws_sagemaker.CfnModel(this, "model",
      {
        executionRoleArn: sagemakerRole.roleArn,
        modelName: "gpu-model",
        primaryContainer: {
          image: getImageUri(isGpuInstance(instanceType)),
          environment: {
            "HF_MODEL_ID": "mrm8488/t5-base-finetuned-question-generation-ap",
            "HF_TASK": "text2text-generation",
          }
        },
      }
    )

    const s3_async_bucket = new cdk.aws_s3.Bucket(this, 'S3Bucket', {
      bucketName: 'test-async-output',
      autoDeleteObjects: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY
    })

    const async_endpoint_config = new cdk.aws_sagemaker.CfnEndpointConfig(
      this, "async_endpoint_config",
      {
        productionVariants: [
          {
            initialInstanceCount: 1,
            initialVariantWeight: 1.0,
            instanceType: instanceType,
            modelName: model.attrModelName,
            variantName: "variantName",
          }
        ],
        asyncInferenceConfig: {
          outputConfig: { s3OutputPath: s3_async_bucket.bucketArn },
          clientConfig: { maxConcurrentInvocationsPerInstance: 123 },
        }
      }
    )

    const async_endpoint = new cdk.aws_sagemaker.CfnEndpoint(this, 'MyEndpoint', {
      endpointConfigName: 'MyEndpointConfig',
      endpointName: 'MyEndpoint',
    })

    async_endpoint_config.node.addDependency(model)
    async_endpoint.node.addDependency(async_endpoint_config)
  }
}
```

</details>

and here is the commands : 

```
aws ecr get-login-password --region MyRegion --profile MyProfile | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-east-1.amazonaws.com

npx cdk deploy MyStackName --profile MyProfile --progress events   
```
Which leads to : 

```
Role arn:aws:iam::MyAcountId:role/TheRoleName cannot pull 
763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04. 
Ensure that the role exists and the image was granted pull permission. 
(Service: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Request ID: 2252f3a9-2246-48d2-9050-7c9696d70307; Proxy: null)
```

As to pull the pre-made image, one as to log in as described here : https://github.com/aws/deep-learning-containers/blob/master/available_images.md#available-deep-learning-containers-images 

Do you have any insights on that ? 

Thanks a lot in advance, 
Have a great day.

**Comment by philschmid** [comment]
Thank you @Ierezell. 

Normally you don't need to log into the ecr locally this should be done during the deployment. Is the error raised by the docker login or by the cdk deploy?

**Comment by ierezell** [comment]
Hi @philschmid, 

Thanks for the fast reply! 

The error arises when doing the `cdk deploy`. However, the role used is the one create and I placed the same permission (even more with some `*`)


**Locally** (on my machine in command line, no cdk) I can pull the image (so it exists). But I have to do the `aws ecs ... | docker login...` else I got a `Error response from daemon: pull access denied for 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference-neuron, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and try again.` which seems clear and works perfectly once logged. 

Thanks again for your help :)

**Comment by philschmid** [comment]
does my python version work for you?

**Comment by ierezell** [comment]
I updated to CDK V2 (as V1 is deprecated since 1st of June) 

Running `cdk deploy ...` raises :
```
AWS CDK v1 has entered maintenance mode
	Overview: AWS CDK v1 has entered maintenance mode on June 1, 2022.
	          Migrate to AWS CDK v2 to continue to get the latest features
	          and fixes!
	Affected versions: framework: 1.*, cli: 1.*
	More information at: https://github.com/aws/aws-cdk/issues/19836
```

Migrating is straightforward, it's just importing `import aws-cdk as cdk` (using `cdk.xx` instead of `core.xx`) and `from constructs import Construct`. Other imports (like `from aws_cdk.s3 import ...` are fine) and having only one dependency : `aws-cdk-lib`.


Using V2 (on the readme example, after a bootstrap) I got : 
```
cdk deploy --parameters model="distilbert-base-uncased-finetuned-sst-2-english" --parameters task="text-classification" --profile MyProfile

✨  Synthesis time: 4.79s

This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬─────────────────────────────┬────────┬─────────────────────────────┬─────────────────────────────┬───────────┐
│   │ Resource                    │ Effect │ Action                      │ Principal                   │ Condition │
├───┼─────────────────────────────┼────────┼─────────────────────────────┼─────────────────────────────┼───────────┤
│ + │ ${hf_sagemaker_execution_ro │ Allow  │ sts:AssumeRole              │ Service:sagemaker.amazonaws │           │
│   │ le.Arn}                     │        │                             │ .com                        │           │
├───┼─────────────────────────────┼────────┼─────────────────────────────┼─────────────────────────────┼───────────┤
│ + │ *                           │ Allow  │ cloudwatch:GetMetricData    │ AWS:${hf_sagemaker_executio │           │
│   │                             │        │ cloudwatch:GetMetricStatist │ n_role}                     │           │
│   │                             │        │ ics                         │                             │           │
│   │                             │        │ cloudwatch:ListMetrics      │                             │           │
│   │                             │        │ cloudwatch:PutMetricData    │                             │           │
│   │                             │        │ ecr:BatchCheckLayerAvailabi │                             │           │
│   │                             │        │ lity                        │                             │           │
│   │                             │        │ ecr:BatchGetImage           │                             │           │
│   │                             │        │ ecr:GetAuthorizationToken   │                             │           │
│   │                             │        │ ecr:GetDownloadUrlForLayer  │                             │           │
│   │                             │        │ logs:CreateLogGroup         │                             │           │
│   │                             │        │ logs:CreateLogStream        │                             │           │
│   │                             │        │ logs:DescribeLogStreams     │                             │           │
│   │                             │        │ logs:GetLogEvents           │                             │           │
│   │                             │        │ logs:PutLogEvents           │                             │           │
│   │                             │        │ s3:CreateBucket             │                             │           │
│   │                             │        │ s3:GetBucketLocation        │                             │           │
│   │                             │        │ s3:GetObject                │                             │           │
│   │                             │        │ s3:ListBucket               │                             │           │
│   │                             │        │ s3:PutObject                │                             │           │
│   │                             │        │ sagemaker:*                 │                             │           │
└───┴─────────────────────────────┴────────┴─────────────────────────────┴─────────────────────────────┴───────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
HuggingfaceSagemaker: deploying...
[0%] start: Publishing f4e177e19b9d7324a4290c0b55412d8aba57f810f68905fd9f38342f7ed79d9d:673333201911-us-east-1
[100%] success: Published f4e177e19b9d7324a4290c0b55412d8aba57f810f68905fd9f38342f7ed79d9d:673333201911-us-east-1
HuggingfaceSagemaker: creating CloudFormation changeset...
11:53:02 | CREATE_FAILED        | AWS::SageMaker::Model          | hfmodel
Role arn:aws:iam::673333201911:role/HuggingfaceSagemaker-hfsagemakerexecutionrole6481F-13C89H7FBRDG3 cannot pull
763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.8.1-transformers4.10.2-cpu-py36-ubuntu1
8.04. Ensure that the role exists and the image was granted pull permission. (Service: AmazonSageMaker; Status Code:
400; Error Code: ValidationException; Request ID: 3bdeaa33-2437-43ae-bfbc-ad4aa5e2bd13; Proxy: null)


 ❌  HuggingfaceSagemaker failed: Error: The stack named HuggingfaceSagemaker failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Role arn:aws:iam::673333201911:role/HuggingfaceSagemaker-hfsagemakerexecutionrole6481F-13C89H7FBRDG3 cannot pull 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.8.1-transformers4.10.2-cpu-py36-ubuntu18.04. Ensure that the role exists and the image was granted pull permission. (Service: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Request ID: 3bdeaa33-2437-43ae-bfbc-ad4aa5e2bd13; Proxy: null)
    at prepareAndExecuteChangeSet (/home/pedro/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:386:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/pedro/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:210:24)
    at initCommandLine (/home/pedro/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/cli.ts:347:12)

The stack named HuggingfaceSagemaker failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Role arn:aws:iam::673333201911:role/HuggingfaceSagemaker-hfsagemakerexecutionrole6481F-13C89H7FBRDG3 cannot pull 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.8.1-transformers4.10.2-cpu-py36-ubuntu18.04. Ensure that the role exists and the image was granted pull permission. (Service: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Request ID: 3bdeaa33-2437-43ae-bfbc-ad4aa5e2bd13; Proxy: null)
```

Which is the same error... Maybe V2 broke something ?

**Comment by ierezell** [comment]
@philschmid I found the culprit. 

The "hack" is to first create only the role and comment stack for models & endpoint. Then uncomment the model and endpoint and deploy again. 

This way, the role is well created before and can be found when creating the model. 

Maybe adding a dependency between the role and the model could make the "one shot deploy" work... 

EDIT : `TheCfnModel.node.addDependency(TheSagemakerRole)` solves the problem. 
I guess that the cdkV2 was not able to find the dependency by itself... 
With this fix I guess we can close the issue, you can either change it easily or I can do a PR. 

Hope that it will help someone. 

Thanks again for the fast help :)
